### ISSUE TITLE
can't get Forge server to start

### ISSUE THREAD

**Issue by Marshin386** [itzg/docker-minecraft-server#1260]
### Describe the problem

I'm using a Stack for a vanilla server and that works perfectly (thank you for all your hard work, its much appreciated), but when I add the environment variable TYPE=FORGE it won't start. I have posted the issue to the Forge forum, but they said I needed to bring the issue to you instead.

I've included the stack that I'm using.

I turned on debug but I didn't get a debug log. however here is what the output in docker is giving me when I try to start the server with the Forge variable included

"
+ return 1
+ exec mc-server-runner --stop-duration 60s --named-pipe /tmp/minecraft-console-in java -Xmx8G -Xms8G -jar /data/run.sh
Error: Invalid or corrupt jarfile /data/run.sh
2022-01-08T01:16:57.983Z	WARN	mc-server-runner	sub-process failed	{"exitCode": 1}
2022-01-08T01:16:57.983Z	INFO	mc-server-runner	Done
+ export HOME=/data
+ HOME=/data
++ id -u
++ id -g
++ ls -lnd /data
+ log 'Running as uid=1000 gid=1000 with /data as '\''drwxrwsrwx 7 1000 1000 4096 Jan  8 01:16 /data'\'''
+ echo '[init] Running as uid=1000 gid=1000 with /data as '\''drwxrwsrwx 7 1000 1000 4096 Jan  8 01:16 /data'\'''
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwsrwx 7 1000 1000 4096 Jan  8 01:16 /data'
+ '[' '!' -e /data/eula.txt ']'
+ [[ -n '' ]]
+ [[ -n '' ]]
+ which java
+ export VERSIONS_JSON=https://launchermeta.mojang.com/mc/game/version_manifest.json
+ VERSIONS_JSON=https://launchermeta.mojang.com/mc/game/version_manifest.json
+ case "X$VERSION" in
++ get --json-path '$.latest.release' https://launchermeta.mojang.com/mc/game/version_manifest.json
++ flags=()
++ local flags
++ isTrue false
++ local value=false
++ result=
++ case ${value} in
++ result=1
++ return 1
++ mc-image-helper get --json-path '$.latest.release' https://launchermeta.mojang.com/mc/game/version_manifest.json
+ VANILLA_VERSION=1.18.1
+ export VANILLA_VERSION
[init] Resolved version given LATEST into 1.18.1
+ log 'Resolved version given LATEST into 1.18.1'
+ echo '[init] Resolved version given LATEST into 1.18.1'
+ cd /data
+ export ORIGINAL_TYPE=FORGE
+ ORIGINAL_TYPE=FORGE
+ isTrue false
+ local value=false
=
+ case ${value} in
+ result=1
+ return 1
+ versionLessThan 1.7
+ local activeParts
+ version=1.18.1
+ version=1.18.1
+ IFS=.
+ read -ra activeParts
+ local givenParts
+ IFS=.
+ read -ra givenParts
+ (( 3 < 2 ))
+ (( 3 == 2 ))
+ (( activeParts[0] < givenParts[0] ))
+ (( activeParts[0] == givenParts[0] && activeParts[1] < givenParts[1] ))
+ (( activeParts[0] == givenParts[0] && activeParts[1] == givenParts[1] && activeParts[2] < givenParts[2] ))
+ return 1
+ log 'Resolving type given FORGE'
+ echo '[init] Resolving type given FORGE'
[init] Resolving type given FORGE
+ case "${TYPE^^}" in
+ versionLessThan 1.17
+ local activeParts
+ version=1.18.1
+ version=1.18.1
+ IFS=.
+ read -ra activeParts
+ local givenParts
+ IFS=.
+ read -ra givenParts
+ (( 3 < 2 ))
+ (( 3 == 2 ))
+ (( activeParts[0] < givenParts[0] ))
+ (( activeParts[0] == givenParts[0] && activeParts[1] < givenParts[1] ))
+ (( activeParts[0] == givenParts[0] && activeParts[1] == givenParts[1] && activeParts[2] < givenParts[2] ))
+ return 1
+ exec /start-deployForge
+ resolve_versions
+ [[ -z '' ]]
+ [[ -z '' ]]
+ norm=1.18.1
+ case $VANILLA_VERSION in
+ norm=1.18.1
+ promosUrl=http://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json
+ log 'Checking Forge version information.'
+ echo '[init] Checking Forge version information.'
+ case $FORGEVERSION in
[init] Checking Forge version information.
++ get -s --json-path '.promos['\''1.18.1-recommended'\'']' http://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json
++ flags=()
++ local flags
++ isTrue false
++ local value=false
++ result=
++ case ${value} in
++ result=1
++ return 1
++ mc-image-helper get -s --json-path '.promos['\''1.18.1-recommended'\'']' http://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json
"

### Container definition

```
version: "2"
services:
  minecraft-server:
    image: itzg/minecraft-server:java17
    container_name: MC118
    network_mode: host
    environment:
      - PUID=998
      - PGID=100
      - EULA=TRUE
      - VERSION=LATEST
      - MEMORY=8G
      - ANNOUNCE_PLAYER_ACHIEVEMENTS=true
      - ALLOW_NETHER=true
      - GENERATE_STRUCTURES=true
      - PVP=false
      - TYPE=FORGE
    ports:
      - 25565:25565
    volumes:
      - /srv/dev-disk-by-label-data/MC118:/data
    restart: unless-stopped
```

### Container logs

```
Paste logs here
```

**Comment by itzg** [comment]
Those logs are actually showing debugs. Unfortunately you missed part of the startup I wanted to see since I am not able to recreate this issue. Can you provide logs all the way from `[init] Running as uid=1000 gid=1000 with /data as 'drwxrwsrwx 7 1000 1000 4096 Jan 8 01:16 /data'` to `INFO mc-server-runner Done`.

Also, please put three back ticks around log blocks since it made a mess of the logs you pasted. I have this section for a reason 😉

![image](https://user-images.githubusercontent.com/988985/148626479-6c119de0-43f6-45e0-89ba-dd957f4cfe3e.png)

**Comment by Marshin386** [comment]
here is the log copied out of the docker log view

new to the forum, sorry.
I attached it as  text file as I'm not completely sure how you wanted the log entered in and don't want to make a mess of the post
[docker log copy.txt](https://github.com/itzg/docker-minecraft-server/files/7832466/docker.log.copy.txt)

**Comment by itzg** [comment]
Thanks for the updated logs. I was able to spot a scenario that was probably missed. See if the latest image now works for you.

**Comment by Marshin386** [comment]
thank you for working on this. however I am still having the same issue.

I cleared the folder of all files and started the container back up and copied out the line from the log view, I have attached them in a text file. please let me know if there is anything else you'd like me to try or change
[docker log 1-8-22.txt](https://github.com/itzg/docker-minecraft-server/files/7833926/docker.log.1-8-22.txt)

here is a picture of the contents of the folder after starting the container.

![image](https://user-images.githubusercontent.com/97071259/148658224-50f2527b-fa04-4fe8-ada6-322603c165d0.png)

.

**Comment by itzg** [comment]
Oops, I forgot you're using the java17 image tag instead of latest (same JVM just separate builds). It's merged over now, so please try again.

**Comment by Marshin386** [comment]
per your comment I tried both keeping the java17 declared and without it being declared. both failed to start but appeared to be for different reasons. I also noticed that Forge just did 2 updates in the last 45 minutes and could be a contributing factor for the server failing to start. please let me know how you would like me to proceed. (we can wait till they have a stable version, or I can run it either of the 2 ways mentioned and provide the log.... or what you think would be best)

**Comment by itzg** [comment]
Sounds like I have fixed all I can, so it's up to you.

**Comment by Marshin386** [comment]
I was asking you which way you wanted me to run it and provide the log.

I have since ran with without the FORGE and and the java17 call, and I can tell you that it wont start, but that isn't new to me. 

after adding the java17 call it will start the vanilla server, but when I add the FORGE setting it is still failing to start.

I have attached the debug log file
[docker log 1-10-22.txt](https://github.com/itzg/docker-minecraft-server/files/7842916/docker.log.1-10-22.txt)
.

**Comment by itzg** [comment]
Are you certain you re-pulled the image? It's showing same behavior as before:

```
+ exec mc-server-runner --stop-duration 60s --named-pipe /tmp/minecraft-console-in java -Xmx2G -Xms2G -jar /data/run.sh
[init] Starting the Minecraft server...
Error: Invalid or corrupt jarfile /data/run.sh
```

**Comment by Marshin386** [comment]
thank you for you help. I deleted the image and re-ran it,

it is now working.

**Comment by thjderjktyrjkt** [comment]
I had this issue when using `java8` image tag (1.12.2 forge), switching to `latest` and forge installation worked, but then server crashes and i had to switch back to `java8` and reuse existing `/data` (with forge installed) then the server starts as normal.
