### ISSUE TITLE
Using AUTO_CURSEFORGE should exclude client mods

### ISSUE THREAD

**Issue by itzg** [itzg/docker-minecraft-server#1893]
@itzg I have tried referencing the ATM pack per the docs for ATM8 1.0.8 referencing by both the CF_FILE_ID=4322138 and also using CF_FILENAME_MATCHER=1.0.8 - it appears that it grabs all the mods from the manifest which also include client side mods (specifically oculus) which results in errors. Commenting on here because it seems related. Is there anything we need to do specifically to make it grab only the server mods that would be included in that server-files zip rather than all the mods from the manifest?

Stacktrace below:

Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:55) ~[forge-1.19.2-43.2.3-universal.jar%23764!/:?] {re:classloading}
	at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:39) ~[forge-1.19.2-43.2.3-universal.jar%23764!/:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:113) ~[server-1.19.2-20220805.130853-srg.jar%23759!/:?] {re:classloading,re:mixin,pl:mixin:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:29) ~[fmlloader-1.19.2-43.2.3.jar%2367!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Stacktrace:
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.19.2-43.2.3.jar%2367!/:1.0] {}
-- MOD oculus --
Details:
	Mod File: /data/mods/oculus-mc1.19.2-1.2.8a.jar
	Failure message: Oculus (oculus) has failed to load correctly
		java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/screens/Screen for invalid dist DEDICATED_SERVER
	Mod Version: 1.2.8a
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/screens/Screen for invalid dist DEDICATED_SERVER
Stacktrace:
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.19.2-43.2.3.jar%2367!/:1.0] {}
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.4.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.4.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.4.jar:?] {}
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?] {}
	at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:?] {re:mixin}
	at java.lang.Class.privateGetDeclaredConstructors(Unknown Source) ~[?:?] {re:mixin}
	at java.lang.Class.getConstructor0(Unknown Source) ~[?:?] {re:mixin}
	at java.lang.Class.getDeclaredConstructor(Unknown Source) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.2-43.2.3.jar%23761!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.2.3.jar%23760!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?] {re:mixin}

_Originally posted by @tmkempster in https://github.com/itzg/docker-minecraft-server/issues/1891#issuecomment-1378237872_

**Comment by ImVexed** [comment]
This is also happening with Vault hunters:
```
      CF_SLUG: vault-hunters-1-18-2
      CF_FILE_ID: 4326051
```

If I specify the file id for the server pack I get:
```
ftb-vault-mc-1  | [init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 2 1000 1000 4096 Jan 12 00:44 /data'
ftb-vault-mc-1  | [init] Resolved version given LATEST into 1.19.3 and major version 1.19
ftb-vault-mc-1  | [init] Resolving type given AUTO_CURSEFORGE
ftb-vault-mc-1  | [mc-image-helper] 00:45:17.499 INFO  : Processing modpack Vault Hunters 3rd Edition-update-5_Server.zip @ 711537:4326051
ftb-vault-mc-1  | [mc-image-helper] 00:45:27.371 ERROR : 'install-curseforge' command failed
ftb-vault-mc-1  | me.itzg.helpers.errors.GenericException: Modpack is missing manifest.json
ftb-vault-mc-1  |       at me.itzg.helpers.curseforge.CurseForgeInstaller.extractModpackManifest(CurseForgeInstaller.java:285)
ftb-vault-mc-1  |       at me.itzg.helpers.curseforge.CurseForgeInstaller.processModpackFile(CurseForgeInstaller.java:166)
ftb-vault-mc-1  |       at me.itzg.helpers.curseforge.CurseForgeInstaller.processMod(CurseForgeInstaller.java:104)
ftb-vault-mc-1  |       at me.itzg.helpers.curseforge.CurseForgeInstaller.install(CurseForgeInstaller.java:70)
ftb-vault-mc-1  |       at me.itzg.helpers.curseforge.InstallCurseForgeCommand.call(InstallCurseForgeCommand.java:68)
ftb-vault-mc-1  |       at me.itzg.helpers.curseforge.InstallCurseForgeCommand.call(InstallCurseForgeCommand.java:12)
ftb-vault-mc-1  |       at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
ftb-vault-mc-1  |       at picocli.CommandLine.access$1500(CommandLine.java:148)
ftb-vault-mc-1  |       at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
ftb-vault-mc-1  |       at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
ftb-vault-mc-1  |       at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
ftb-vault-mc-1  |       at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
ftb-vault-mc-1  |       at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
ftb-vault-mc-1  |       at picocli.CommandLine.execute(CommandLine.java:2170)
ftb-vault-mc-1  |       at me.itzg.helpers.McImageHelper.main(McImageHelper.java:104)
ftb-vault-mc-1  | [init] ERROR failed to auto-install CurseForge modpack
```

But if I don't specify the server file, and let it auto resolve, it fails to load a client side mod:
```
ftb-vault-mc-1  | A detailed walkthrough of the error, its code path and all known details is as follows:
ftb-vault-mc-1  | ---------------------------------------------------------------------------------------
ftb-vault-mc-1  |
ftb-vault-mc-1  | -- Head --
ftb-vault-mc-1  | Thread: main
ftb-vault-mc-1  | Stacktrace:
ftb-vault-mc-1  |       at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.18.2-40.1.93.jar%2317!/:1.0] {}
ftb-vault-mc-1  | -- MOD torohealth --
ftb-vault-mc-1  | Details:
ftb-vault-mc-1  |       Caused by 0: java.lang.ExceptionInInitializerError
ftb-vault-mc-1  |               at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
ftb-vault-mc-1  |               at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {}
ftb-vault-mc-1  |               at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {}
ftb-vault-mc-1  |               at java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?] {}
ftb-vault-mc-1  |               at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?] {}
ftb-vault-mc-1  |               at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:67) ~[javafmllanguage-1.18.2-40.1.93.jar%23173!/:?] {}
ftb-vault-mc-1  |               at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:106) ~[fmlcore-1.18.2-40.1.93.jar%23172!/:?] {}
ftb-vault-mc-1  |               at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?] {}
ftb-vault-mc-1  |               at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:?] {}
ftb-vault-mc-1  |               at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?] {}
ftb-vault-mc-1  |               at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?] {}
ftb-vault-mc-1  |               at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?] {}
ftb-vault-mc-1  |               at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?] {}
ftb-vault-mc-1  |               at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?] {}
ftb-vault-mc-1  |
ftb-vault-mc-1  |       Mod File: /data/mods/torohealth-1.18-forge-2.jar
ftb-vault-mc-1  |       Failure message: ToroHealth (torohealth) has failed to load correctly
ftb-vault-mc-1  |               java.lang.ExceptionInInitializerError: null
ftb-vault-mc-1  |       Mod Version: 1.18-forge-2
ftb-vault-mc-1  |       Mod Issue URL: https://github.com/ToroCraft/ToroHealth/issues
ftb-vault-mc-1  |       Exception message: java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/screens/Screen for invalid dist DEDICATED_SERVER
```

**Comment by tmkempster** [comment]
It appears the fix has already been made in mc-image-helper - as soon as that version is updated in the docker-minecraft-server it should be resolved based on what I am seeing.

@itzg I can make this change however I am unable to make branches/contributions. How would I go about getting access to do so?

**Comment by itzg** [comment]
Thanks @tmkempster for the offer but I almost have the change finished up. I'm also trying to address dependency resolution, which is what is holding this up.

**Comment by itzg** [comment]
...and FYI, I had fixed it incorrectly before this PR does it the right way:

https://github.com/itzg/mc-image-helper/pull/89

**Comment by itzg** [comment]
Latest image now downloads only server mods, but ATM8 is still not working since dependency mods/libraries are also needing to be grabbed. As of now I hit this kind of error:

```
[14:29:15] [main/WARN] [mixin/]: Error loading class: com/teamresourceful/resourcefullib/common/registry/RegistryEntry (java.lang.ClassNotFoundException: com.teamresourceful.resourcefullib.common.registry.RegistryEntry)
Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
```

**Comment by DrWhoCares** [comment]
Vault Hunters is still broken due to ToroHealth and LegendaryTooltips being client-side mods but not being labeled as such, so I assume your fix doesn't exclude them.

**Comment by itzg** [comment]
@DrWhoCares unfortunately a number of mods have not correctly denoted client-only. That's why I had to introduce the `CF_EXCLUDE_MODS` as described in

https://github.com/itzg/docker-minecraft-server#auto-curseforge-management

I can (or anyone can PR) add those mods into the default exclusions.

Reporting an issue with the mod authors would be great too. They simply need to add "client" to the game versions declaration.

**Comment by itzg** [comment]
Default exclusions are maintained here, for anyone interested in contributing 

https://github.com/itzg/docker-minecraft-server/blob/master/scripts/start-deployAutoCF#L38

**Comment by itzg** [comment]
Speaking of reporting issues, mod authors need to carefully re-read the sides and levels concept and implement proper detection as described in the official Forge documentation 

https://docs.minecraftforge.net/en/latest/concepts/sides/#writing-one-sided-mods

**Comment by DrWhoCares** [comment]
I've added the line `CF_EXCLUDE_MODS: "3556931,4035921"` which should be the IDs for the two mods, going based off what's being output from the crash report in the logs, but they're still erroring. The docs simply say, "passing a comma or space delimited list of project IDs via `CF_EXCLUDE_MODS`"
Am I doing something wrong with the syntax? There's no examples in the readme. I'm using docker-compose specifically. Do I need to do anything like removing the image and re-pulling it or something like that?

**Comment by itzg** [comment]
Try setting `CF_FORCE_SYNCHRONIZE: "true"`, which is described at end of section.

**Comment by DrWhoCares** [comment]
That did not solve the issue unfortunately. It went through all the mods, said they all already exist, and then same errors with the two mods.

**Comment by itzg** [comment]
@DrWhoCares , I created a new issue to avoid further chatter on a closed issue. Over there, can you let me know which edition of Vault Hunters you are trying?
