### ISSUE TITLE
MOTD Sanitization Breaks Color Coding (using section mark symbol)

### ISSUE THREAD

**Issue by aaronjamt** [itzg/docker-minecraft-server#2433]
The code around [line 25 of `scripts/start-setupServerProperties`](https://github.com/itzg/docker-minecraft-server/blob/e5f818bdf1448930baef16cb914180002f93fb6d/scripts/start-setupServerProperties#L25) sanitizes the MOTD text, but that causes it to be entirely broken if it contains color or other speciak formatting. All section marks (`§`, the character used by Minecraft as an escape character for processing formatting) are replaced with `Â§` which seems to be something to do with UTF-8 vs UTF-16 encoding. However, this causes text to look very wrong in game, as seen in the image below. Here is an example of what I mean:

This MOTD is supposed to make rainbow text that says "Testing 123":
> `§c§lT§6§le§e§ls§a§lt§3§li§9§ln§5§lg §6§l1§e§l2§a§l3`

However, it gets converted to the following:
> `Â§cÂ§lTÂ§6Â§leÂ§eÂ§lsÂ§aÂ§ltÂ§3Â§liÂ§9Â§lnÂ§5Â§lg Â§6Â§l1Â§eÂ§l2Â§aÂ§l3`

In game, it appears like this:
![image](https://github.com/itzg/docker-minecraft-server/assets/13600347/aac90a8b-09f1-4924-a906-3df3e2f3544a)

**Comment by itzg** [comment]
Thanks for reporting this. It seems to have been a regression introduced by #2414 where the pre-normalizing is no longer needed.

**Comment by LapinFou** [comment]
BTW, I'm using Portainer and I don't understand how to pass the MOTD through an environment variable.
I tried this:
`MOTD=Serveur Minecraft §c§lLa Familia§r`
or this:
`MOTD="Serveur Minecraft §c§lLa Familia§r"`
or this:
`MOTD="Serveur Minecraft \§c\§lLa Familia\§r"`
or this:
`MOTD=\"Serveur Minecraft \§c\§lLa Familia\§r\"`
or this:
`MOTD="Serveur Minecraft \u00c\u00lLa Familia\u00r"`
and this
`MOTD=Serveur Minecraft \u00c\u00lLa Familia\u00r`

None seems to be working. Some weird characters are always added. 😅

**Comment by itzg** [comment]
Yes, that's why @aaronjamt opened this issue. Please be patient while I work out a build issue preventing the code change from being verified.

**Comment by itzg** [comment]
@LapinFou to answer your initial question, after the fix it will work with this format where I am assuming you are using `docker run`:

```
docker run -it -e EULA=true -e MOTD="Serveur Minecraft §c§lLa Familia§r" -p 25565:25565 itzg/minecraft-server
```

**Comment by itzg** [comment]
The fix has been merged. Watch this build to see when the new image can be pulled https://github.com/itzg/docker-minecraft-server/actions/runs/6512997592

**Comment by LapinFou** [comment]
@itzg thanks a lot! 👍
I was also asking the question because I hacked my current container by removing those 3 lines as shown here https://github.com/itzg/docker-minecraft-server/commit/2ebcc0fe0051fee282f70a9c6ed5f746d59d1c4f
```
  if [[ $MOTD ]]; then
    MOTD="$(echo "$MOTD" | mc-image-helper asciify)"
  fi
```
But, it didn't fix the problem. Thus, I was wondering if I wasn't missing something else. 😅

**Comment by itzg** [comment]
Ah ok. Let me know if it is still not working with the latest image. I noticed it was odd during my testing that the server itself would switch out the value in the properties file, so a problem might still be lurking there.

**Comment by aaronjamt** [comment]
I greatly appreciate you taking the time to try to resolve this issue and I apologize for the late reply. I just installed the updated version from Docker Hub and it's having the same issue still. While checking it again just now, I noticed that for a brief moment the file is converted to:
> `motd=\u00C2\u00A7c\u00C2\u00A7lT\u00C2\u00A76\u00C2\u00A7le\u00C2\u00A7e\u00C2\u00A7ls\u00C2\u00A7a\u00C2\u00A7lt\u00C2\u00A73\u00C2\u00A7li\u00C2\u00A79\u00C2\u00A7ln\u00C2\u00A75\u00C2\u00A7lg \u00C2\u00A76\u00C2\u00A7l1\u00C2\u00A7e\u00C2\u00A7l2\u00C2\u00A7a\u00C2\u00A7l3`

Then, it appears the actual Minecraft server software (using Folia in this case) converts _that_ to:
> `motd=Â§cÂ§lTÂ§6Â§leÂ§eÂ§lsÂ§aÂ§ltÂ§3Â§liÂ§9Â§lnÂ§5Â§lg Â§6Â§l1Â§eÂ§l2Â§aÂ§l3`

Are there any other steps I can take to troubleshoot this?

**Comment by itzg** [comment]
@aaronjamt I'll re-test this also but can you provide the compose file you're using or at least just the MOTD line? Also, setting `DEBUG` to "true" and providing the logs before the Minecraft server is started could help.

**Comment by itzg** [comment]
This compose file just now worked for me:

```yaml
version: "3.8"

services: 
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: true
      MOTD: §c§lT§6§le§e§ls§a§lt§3§li§9§ln§5§lg §6§l1§e§l2§a§l3
    ports:
    - "25565:25565"
    volumes:
    - ./data:/data 
```

and saw my `server.properties` go from during this during container init

```
motd=\u00A7c\u00A7lT\u00A76\u00A7le\u00A7e\u00A7ls\u00A7a\u00A7lt\u00A73\u00A7li\u00A79\u00A7ln\u00A75\u00A7lg \u00A76\u00A7l1\u00A7e\u00A7l2\u00A7a\u00A7l3
```

to this during server startup

```
motd=§c§lT§6§le§e§ls§a§lt§3§li§9§ln§5§lg §6§l1§e§l2§a§l3
```

If you're using compose, perhaps double check your compose file is using UTF-8.

**Comment by aaronjamt** [comment]
I'm using UnRAID (so not Docker Compose) and I'm not passing the MOTD in the Docker command or environment variables, I've just put the MOTD in the `server.properties` file like you normally would for a vanilla server. Until I updated 2 days ago, it worked fine, but after the update I've been having issues. I'll try to start it with the `DEBUG` flag soon, although it might be a few hours until I'm able to do so.

**Comment by itzg** [comment]
Can you double check that you have the latest image re-pulled? I tried a few more experiments and the only way I could "break" it was to set `MOTD` to the pre-escaped version 

```
      MOTD: \u00A7c\u00A7lT\u00A76\u00A7le\u00A7e\u00A7ls\u00A7a\u00A7lt\u00A73\u00A7li\u00A79\u00A7ln\u00A75\u00A7lg \u00A76\u00A7l1\u00A7e\u00A7l2\u00A7a\u00A7l3
```

and it would double escape the backslashes:

![image](https://github.com/itzg/docker-minecraft-server/assets/988985/f805917c-448a-41c9-aef9-c3683cfeaab0)

I'll see if I can address that, but I know that's different than your scenario.

**Comment by aaronjamt** [comment]
I just pulled the latest image again, same issue. Here's a full list of steps that reproduces this issue:


1. Run the container (the mounted folder for `/data` doesn't exist, Docker will create it and the container will populate it)
```
docker run
  -d
  --name='MinecraftTestFolia'
  --net='docker-internal'
  -e TZ="REDACTED"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="REDACTED"
  -e HOST_CONTAINERNAME="MinecraftTestFolia"
  -e 'EULA'='TRUE'
  -e 'TYPE'='FOLIA'
  -e 'MEMORY'='1G'
  -e 'USE_AIKAR_FLAGS'='true'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/fithwum/files-for-dockers/master/icons/minecraft.png'
  -p '25565:25565/tcp'
  -v '/mnt/user/appdata/MinecraftServer/TestFolia2':'/data':'rw'
  'itzg/minecraft-server:latest'
```

2. Once container is started and appears in server list, shut it down (I waited around 5 minutes to make sure it was fully started). Here is how it appears:
![image](https://github.com/itzg/docker-minecraft-server/assets/13600347/72a9d04a-81bf-4fc0-9469-a9dfdc302af7)

3. Check logs of container
```
[init] Changing ownership of /data to 1000 ...
[init] Running as uid=1000 gid=1000 with /data as 'drwxr-xr-x 1 1000 1000 10 Oct 15 15:56 /data'
[init] Resolving type given FOLIA
[mc-image-helper] 15:56:50.044 INFO  : Resolved folia to version 1.20.1 build 17
[mc-image-helper] 15:56:52.543 INFO  : Downloaded /data/folia-1.20.1-17.jar
[init] Creating server properties in /data/server.properties
[init] Disabling whitelist functionality
[mc-image-helper] 15:56:54.763 INFO  : Created/updated 4 properties in /data/server.properties
[init] Using Aikar's flags
[init] Setting initial memory to 1G and max to 1G
[init] Starting the Minecraft server...
Downloading mojang_1.20.1.jar
Applying patches
Starting org.bukkit.craftbukkit.Main
*** Warning, you've not updated in a while! ***
*** Please download a new build as per instructions from https://papermc.io/downloads/paper ***
System Info: Java 17 (OpenJDK 64-Bit Server VM 17.0.8.1+1) Host: Linux 6.1.49-Unraid (amd64)
Loading libraries, please wait...
2023-10-15 15:57:11,881 ServerMain WARN Advanced terminal features are not available in this environment
[15:57:18 INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[15:57:18 INFO]: Found new data pack file/bukkit, loading it automatically
[15:57:20 INFO]: Loaded 7 recipes
[15:57:20 INFO]: Starting minecraft server version 1.20.1
[15:57:20 INFO]: Loading properties
[15:57:21 INFO]: This server is running Folia version git-Folia-17 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: edafbce)
[15:57:21 INFO]: Server Ping Player Sample Count: 12
[15:57:21 INFO]: Using 4 threads for Netty based IO
[15:57:21 INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 14 worker threads, and gen parallelism of 14 threads
[15:57:21 WARN]: [!] The timings system cannot be enabled on Folia, and has been scheduled for removal from Paper in the future.
    We recommend installing the spark profiler as a replacement: https://spark.lucko.me/
    For more information please visit: https://github.com/PaperMC/Paper/issues/8948
[15:57:21 INFO]: [io.papermc.paper.threadedregions.TickRegions] Regionised ticking is enabled with 7 tick threads
[15:57:21 INFO]: Default game type: SURVIVAL
[15:57:21 INFO]: Generating keypair
[15:57:21 INFO]: Starting Minecraft server on *:25565
[15:57:21 INFO]: Using epoll channel type
[15:57:21 INFO]: Paper: Using libdeflate (Linux x86_64) compression from Velocity.
[15:57:21 INFO]: Paper: Using OpenSSL 1.1.x (Linux x86_64) cipher from Velocity.
[15:57:21 INFO]: Preparing level "world"
[15:57:22 INFO]: Preparing start region for dimension minecraft:overworld
[15:57:22 INFO]: Time elapsed: 10 ms
[15:57:22 INFO]: Preparing start region for dimension minecraft:the_nether
[15:57:22 INFO]: Time elapsed: 3 ms
[15:57:22 INFO]: Preparing start region for dimension minecraft:the_end
[15:57:22 INFO]: Time elapsed: 2 ms
[15:57:22 INFO]: Starting remote control listener
[15:57:22 INFO]: Thread RCON Listener started
[15:57:22 INFO]: RCON running on 0.0.0.0:25575
[15:57:22 INFO]: Done (1.790s)! For help, type "help"
[15:57:22 INFO]: Initialising world 'world' before it can be ticked...
[15:57:22 INFO]: Initialising world 'world_nether' before it can be ticked...
[15:57:23 INFO]: Initialising world 'world_the_end' before it can be ticked...
[15:57:23 INFO]: Initialised world 'world_the_end'
[15:57:23 INFO]: Timings Reset
[15:57:25 INFO]: Initialised world 'world'
[15:57:26 INFO]: Initialised world 'world_nether'
2023/10/15 16:01:47 Stopping with rcon-cli
[16:01:47 INFO]: Thread RCON Client /127.0.0.1 started
[16:01:47 INFO]: Thread RCON Client /127.0.0.1 shutting down
2023-10-15T16:01:47.481-0700	INFO	mc-server-runner	Waiting for completion...
```

4. Edit `server.properties` file and set the `motd=` parameter to `§c§lT§6§le§e§ls§a§lt§3§li§9§ln§5§lg §6§l1§e§l2§a§l3`:
```
#Minecraft server properties
#Sun Oct 15 15:57:18 PDT 2023
enable-jmx-monitoring=false
rcon.port=25575
level-seed=
gamemode=survival
enable-command-block=false
enable-query=false
generator-settings={}
enforce-secure-profile=true
level-name=world
motd=§c§lT§6§le§e§ls§a§lt§3§li§9§ln§5§lg §6§l1§e§l2§a§l3
query.port=25565
pvp=true
generate-structures=true
max-chained-neighbor-updates=1000000
difficulty=easy
network-compression-threshold=256
max-tick-time=60000
require-resource-pack=false
use-native-transport=true
max-players=20
online-mode=true
enable-status=true
allow-flight=false
initial-disabled-packs=
broadcast-rcon-to-ops=true
view-distance=10
server-ip=
resource-pack-prompt=
allow-nether=true
server-port=25565
enable-rcon=true
sync-chunk-writes=true
op-permission-level=4
prevent-proxy-connections=false
hide-online-players=false
resource-pack=
entity-broadcast-range-percentage=100
simulation-distance=10
rcon.password=a66f23c77b06422ec58dca39
player-idle-timeout=0
debug=false
force-gamemode=false
rate-limit=0
hardcore=false
white-list=false
broadcast-console-to-ops=true
spawn-npcs=true
spawn-animals=true
function-permission-level=2
initial-enabled-packs=vanilla
level-type=minecraft\:normal
text-filtering-config=
spawn-monsters=true
enforce-whitelist=false
spawn-protection=16
resource-pack-sha1=
max-world-size=29999984
```

5. Start container again and check Minecraft:
![image](https://github.com/itzg/docker-minecraft-server/assets/13600347/ed589ebc-cd29-478d-ba6a-c3e5db07c1a4)

6. Check container logs (specifically the logs from the second time the container was started)
```
[init] Running as uid=1000 gid=1000 with /data as 'drwxr-xr-x 1 1000 1000 4096 Oct 15 15:57 /data'
[init] Resolving type given FOLIA
[mc-image-helper] 16:04:21.772 INFO  : Resolved folia to version 1.20.1 build 17
[mc-image-helper] 16:04:24.002 INFO  : Created/updated 1 property in /data/server.properties
[init] Using Aikar's flags
[init] Setting initial memory to 1G and max to 1G
[init] Starting the Minecraft server...
Starting org.bukkit.craftbukkit.Main
*** Warning, you've not updated in a while! ***
*** Please download a new build as per instructions from https://papermc.io/downloads/paper ***
System Info: Java 17 (OpenJDK 64-Bit Server VM 17.0.8.1+1) Host: Linux 6.1.49-Unraid (amd64)
Loading libraries, please wait...
2023-10-15 16:04:32,676 ServerMain WARN Advanced terminal features are not available in this environment
[16:04:39 INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[16:04:39 INFO]: Found new data pack file/bukkit, loading it automatically
[16:04:41 INFO]: Loaded 7 recipes
[16:04:42 INFO]: Starting minecraft server version 1.20.1
[16:04:42 INFO]: Loading properties
[16:04:42 INFO]: This server is running Folia version git-Folia-17 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: edafbce)
[16:04:42 INFO]: Server Ping Player Sample Count: 12
[16:04:42 INFO]: Using 4 threads for Netty based IO
[16:04:42 WARN]: [!] The timings system cannot be enabled on Folia, and has been scheduled for removal from Paper in the future.
    We recommend installing the spark profiler as a replacement: https://spark.lucko.me/
    For more information please visit: https://github.com/PaperMC/Paper/issues/8948
[16:04:42 INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 14 worker threads, and gen parallelism of 14 threads
[16:04:42 INFO]: [io.papermc.paper.threadedregions.TickRegions] Regionised ticking is enabled with 7 tick threads
[16:04:42 INFO]: Default game type: SURVIVAL
[16:04:42 INFO]: Generating keypair
[16:04:43 INFO]: Starting Minecraft server on *:25565
[16:04:43 INFO]: Using epoll channel type
[16:04:43 INFO]: Paper: Using libdeflate (Linux x86_64) compression from Velocity.
[16:04:43 INFO]: Paper: Using OpenSSL 1.1.x (Linux x86_64) cipher from Velocity.
[16:04:43 INFO]: Server permissions file permissions.yml is empty, ignoring it
[16:04:43 INFO]: Preparing level "world"
[16:04:44 INFO]: Preparing start region for dimension minecraft:overworld
[16:04:44 INFO]: Time elapsed: 12 ms
[16:04:44 INFO]: Preparing start region for dimension minecraft:the_nether
[16:04:44 INFO]: Time elapsed: 3 ms
[16:04:44 INFO]: Preparing start region for dimension minecraft:the_end
[16:04:44 INFO]: Time elapsed: 3 ms
[16:04:44 INFO]: Starting remote control listener
[16:04:44 INFO]: Thread RCON Listener started
[16:04:44 INFO]: RCON running on 0.0.0.0:25575
[16:04:44 INFO]: Done (1.941s)! For help, type "help"
[16:04:44 INFO]: Initialising world 'world' before it can be ticked...
[16:04:44 INFO]: Initialising world 'world_nether' before it can be ticked...
[16:04:44 INFO]: Initialising world 'world_the_end' before it can be ticked...
[16:04:45 INFO]: Initialised world 'world_the_end'
[16:04:45 INFO]: Timings Reset
[16:04:46 INFO]: Initialised world 'world_nether'
[16:04:48 INFO]: Initialised world 'world'
```

7. Check new contents of `server.properties`:
```
#Minecraft server properties
#Sun Oct 15 16:04:39 PDT 2023
enable-jmx-monitoring=false
rcon.port=25575
level-seed=
gamemode=survival
enable-command-block=false
enable-query=false
generator-settings={}
enforce-secure-profile=true
level-name=world
motd=Â§cÂ§lTÂ§6Â§leÂ§eÂ§lsÂ§aÂ§ltÂ§3Â§liÂ§9Â§lnÂ§5Â§lg Â§6Â§l1Â§eÂ§l2Â§aÂ§l3
query.port=25565
pvp=true
generate-structures=true
max-chained-neighbor-updates=1000000
difficulty=easy
network-compression-threshold=256
max-tick-time=60000
require-resource-pack=false
use-native-transport=true
max-players=20
online-mode=true
enable-status=true
allow-flight=false
initial-disabled-packs=
broadcast-rcon-to-ops=true
view-distance=10
server-ip=
resource-pack-prompt=
allow-nether=true
server-port=25565
enable-rcon=true
sync-chunk-writes=true
op-permission-level=4
prevent-proxy-connections=false
hide-online-players=false
resource-pack=
entity-broadcast-range-percentage=100
simulation-distance=10
rcon.password=f750513b4ac98b29e261592a
player-idle-timeout=0
debug=false
force-gamemode=false
rate-limit=0
hardcore=false
white-list=false
broadcast-console-to-ops=true
spawn-npcs=true
spawn-animals=true
function-permission-level=2
initial-enabled-packs=vanilla
level-type=minecraft\:normal
text-filtering-config=
spawn-monsters=true
enforce-whitelist=false
spawn-protection=16
resource-pack-sha1=
max-world-size=29999984
```

**Comment by aaronjamt** [comment]
I forgot to run those with the DEBUG flag, here are the extra logs from running steps 4-6 with the environment variable `DEBUG=true`:
```
+ export HOME=/data
+ HOME=/data
++ id -u
++ id -g
++ ls -lnd /data
+ log 'Running as uid=1000 gid=1000 with /data as '\''drwxr-xr-x 1 1000 1000 4096 Oct 15 15:57 /data'\'''
+ local oldState
++ shopt -po xtrace
+ oldState='set -o xtrace'
+ shopt -u -o xtrace
[init] 2023-10-15 16:10:40-07:00 Running as uid=1000 gid=1000 with /data as 'drwxr-xr-x 1 1000 1000 4096 Oct 15 15:57 /data'
+ '[' '!' -e /data/eula.txt ']'
+ isTrue false
+ case "${1,,}" in
+ return 1
+ isTrue false
+ case "${1,,}" in
+ return 1
+ [[ -n '' ]]
+ [[ -n '' ]]
+ echo password=dbeae0d3979fbe863de3144f
+ fixJavaPath
+ which java
+ cd /data
+ export ORIGINAL_TYPE=FOLIA
+ ORIGINAL_TYPE=FOLIA
+ isTrue false
+ case "${1,,}" in
+ return 1
+ isTrue false
+ case "${1,,}" in
+ return 1
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ : ''
+ case "${TYPE^^}" in
+ [[ -n '' ]]
+ log 'Resolving type given FOLIA'
+ local oldState
++ shopt -po xtrace
+ oldState='set -o xtrace'
+ shopt -u -o xtrace
[init] 2023-10-15 16:10:40-07:00 Resolving type given FOLIA
+ case "${TYPE^^}" in
+ exec /start-deployFolia
+ : folia
+ : ''
+ : ''
+ : ''
+ resultsFile=/data/.paper.env
+ [[ -n '' ]]
+ [[ -n '' ]]
+ args=(--output-directory=/data --results-file="$resultsFile" --project="$PAPER_PROJECT" --version="$VERSION")
+ [[ -n '' ]]
+ mc-image-helper install-paper --output-directory=/data --results-file=/data/.paper.env --project=folia --version=LATEST
[mc-image-helper] 16:10:42.710 DEBUG : JSON FETCH: uri=https://api.papermc.io/v2/projects/folia headers=[user-agent: itzg/mc-image-helper/1.36.2 (cmd=install-paper), x-fetch-session: 01858707-f9e5-4ef3-8194-4f3b90558d77, accept: application/json, host: api.papermc.io]
[mc-image-helper] 16:10:42.968 DEBUG : JSON FETCH: uri=https://api.papermc.io/v2/projects/folia/versions/1.20.1 headers=[user-agent: itzg/mc-image-helper/1.36.2 (cmd=install-paper), x-fetch-session: 01858707-f9e5-4ef3-8194-4f3b90558d77, accept: application/json, host: api.papermc.io]
[mc-image-helper] 16:10:43.188 INFO  : Resolved folia to version 1.20.1 build 17
[mc-image-helper] 16:10:43.202 DEBUG : JSON FETCH: uri=https://api.papermc.io/v2/projects/folia/versions/1.20.1/builds/17 headers=[user-agent: itzg/mc-image-helper/1.36.2 (cmd=install-paper), x-fetch-session: 01858707-f9e5-4ef3-8194-4f3b90558d77, accept: application/json, host: api.papermc.io]
[mc-image-helper] 16:10:43.422 DEBUG : Skipping file=/data/folia-1.20.1-17.jar that already exists due to request
[mc-image-helper] 16:10:43.425 DEBUG : Writing SERVER=/data/folia-1.20.1-17.jar to results file
[mc-image-helper] 16:10:43.426 DEBUG : Writing TYPE=PAPER to results file
[mc-image-helper] 16:10:43.426 DEBUG : Writing VERSION=1.20.1 to results file
+ set -a
+ source /data/.paper.env
++ SERVER=/data/folia-1.20.1-17.jar
++ TYPE=PAPER
++ VERSION=1.20.1
+ set +a
+ export FAMILY=SPIGOT
+ FAMILY=SPIGOT
+ exec /start-spiget
+ : ''
+ : 5
+ : '*.jar,*-version.json'
+ acceptArgs=(--accept application/zip --accept application/java-archive --accept application/octet-stream)
+ [[ -n '' ]]
+ exec /start-setupWorld
+ '[' PAPER = CURSEFORGE ']'
+ worldDest=/data/world
+ [[ -n '' ]]
+ exec /start-setupDatapack
+ out_dir=/data/world/datapacks
+ isTrue false
+ case "${1,,}" in
+ return 1
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ exec /start-setupModpack
+ CURSE_URL_BASE=https://minecraft.curseforge.com/projects
+ isTrue false
+ case "${1,,}" in
+ return 1
+ handlePackwiz
+ [[ -n '' ]]
+ handleModpackZip
+ [[ -n '' ]]
+ handleListings
+ usesMods
+ case "$FAMILY" in
+ return 1
+ usesPlugins
+ case "$FAMILY" in
+ return 0
+ outDir=/data/mods
+ usesPlugins
+ case "$FAMILY" in
+ return 0
+ outDir=/data/plugins
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ handleGenericPacks
+ : ''
+ : ''
+ : ''
+ [[ -n '' ]]
+ handleModrinthProjects
+ : ''
+ : release
+ : none
+ [[ -v MODRINTH_DOWNLOAD_OPTIONAL_DEPENDENCIES ]]
+ [[ -n '' ]]
+ usesMods
+ case "$FAMILY" in
+ return 1
+ usesPlugins
+ case "$FAMILY" in
+ return 0
+ handleCurseForgeFiles
+ args=()
+ usesMods
+ case "$FAMILY" in
+ return 1
+ usesPlugins
+ case "$FAMILY" in
+ return 0
+ usesMods
+ case "$FAMILY" in
+ return 1
+ args+=(--default-category bukkit-plugins)
+ case "${TYPE,,}" in
+ mc-image-helper curseforge-files --default-category bukkit-plugins
+ exec /start-setupModconfig
+ isTrue true
+ case "${1,,}" in
+ return 0
+ updateArg=--skip-newer-in-destination
+ isTrue true
+ case "${1,,}" in
+ return 0
+ subcommand=sync-and-interpolate
+ : /plugins
+ : /data/plugins
+ usesPlugins
+ case "$FAMILY" in
+ return 0
+ '[' -d /plugins ']'
+ : /mods
+ : /data/mods
+ usesMods
+ case "$FAMILY" in
+ return 1
+ : /config
+ : /data/config
+ '[' -d /config ']'
+ exec /start-setupServerProperties
[mc-image-helper] 16:10:45.604 DEBUG : Setting property rcon.password to new value '***'
[mc-image-helper] 16:10:45.607 INFO  : Created/updated 1 property in /data/server.properties
+ [[ -v APPEND_OPS ]]
+ [[ -v OVERRIDE_OPS ]]
+ [[ -v APPEND_WHITELIST ]]
+ [[ -v OVERRIDE_WHITELIST ]]
+ sharedArgs=(--version="$VERSION")
+ isFalse true
+ case "${1,,}" in
+ return 1
+ [[ -v OPS_FILE ]]
+ [[ -v OPS ]]
+ [[ -v WHITELIST_FILE ]]
+ [[ -v WHITELIST ]]
+ exec /start-finalExec
+ '[' -n '' ']'
+ canUseRollingLogs=true
+ useFallbackJvmFlag=false
+ versionLessThan 1.7
+ mc-image-helper compare-versions 1.20.1 lt 1.7
+ return 1
+ isFamily VANILLA
+ for f in "${@}"
+ [[ SPIGOT == \V\A\N\I\L\L\A ]]
+ return 1
+ isFamily VANILLA
+ for f in "${@}"
+ [[ SPIGOT == \V\A\N\I\L\L\A ]]
+ return 1
+ isType PURPUR
+ for t in "${@}"
+ [[ PAPER == \P\U\R\P\U\R ]]
+ return 1
+ isType PURPUR
+ for t in "${@}"
+ [[ PAPER == \P\U\R\P\U\R ]]
+ return 1
+ versionLessThan 1.18.1
+ mc-image-helper compare-versions 1.20.1 lt 1.18.1
+ return 1
+ false
+ versionLessThan 1.7
+ mc-image-helper compare-versions 1.20.1 lt 1.7
+ return 1
+ versionLessThan 1.18.1
+ mc-image-helper compare-versions 1.20.1 lt 1.18.1
+ return 1
+ isTrue false
+ case "${1,,}" in
+ return 1
+ versionLessThan 1.14
+ mc-image-helper compare-versions 1.20.1 lt 1.14
+ return 1
+ [[ '' = false ]]
+ expandedDOpts=
+ '[' -n '' ']'
+ isTrue ''
+ case "${1,,}" in
+ return 1
+ isTrue true
+ case "${1,,}" in
+ return 0
++ normalizeMemSize 1G
++ local scale=1
++ case ${1,,} in
++ scale=1073741824
++ val=1
++ echo 1073741824
++ normalizeMemSize 12g
++ local scale=1
++ case ${1,,} in
++ scale=1073741824
++ val=12
++ echo 12884901888
+ ((  1073741824 >= 12884901888  ))
+ log 'Using Aikar'\''s flags'
+ local oldState
++ shopt -po xtrace
+ oldState='set -o xtrace'
+ shopt -u -o xtrace
[init] 2023-10-15 16:10:49-07:00 Using Aikar's flags
+ G1NewSizePercent=30
+ G1MaxNewSizePercent=40
+ G1HeapRegionSize=8M
+ G1ReservePercent=20
+ InitiatingHeapOccupancyPercent=15
+ JVM_XX_OPTS='
  -XX:+UseG1GC
  -XX:+ParallelRefProcEnabled
  -XX:MaxGCPauseMillis=200
  -XX:+UnlockExperimentalVMOptions
  -XX:+DisableExplicitGC
  -XX:+AlwaysPreTouch
  -XX:G1NewSizePercent=30
  -XX:G1MaxNewSizePercent=40
  -XX:G1HeapRegionSize=8M
  -XX:G1ReservePercent=20
  -XX:G1HeapWastePercent=5
  -XX:G1MixedGCCountTarget=4
  -XX:InitiatingHeapOccupancyPercent=15
  -XX:G1MixedGCLiveThresholdPercent=90
  -XX:G1RSetUpdatingPauseTimePercent=5
  -XX:SurvivorRatio=32
  -XX:+PerfDisableSharedMem
  -XX:MaxTenuringThreshold=1
  -Dusing.aikars.flags=https://mcflags.emc.gs
  -Daikars.new.flags=true
  '
+ isTrue ''
+ case "${1,,}" in
+ return 1
+ isTrue ''
+ case "${1,,}" in
+ return 1
+ isTrue ''
+ case "${1,,}" in
+ return 1
+ [[ -n 1G ]]
+ log 'Setting initial memory to 1G and max to 1G'
+ local oldState
++ shopt -po xtrace
+ oldState='set -o xtrace'
+ shopt -u -o xtrace
[init] 2023-10-15 16:10:49-07:00 Setting initial memory to 1G and max to 1G
+ [[ -n 1G ]]
+ JVM_OPTS='-Xms1G '
+ [[ -n 1G ]]
+ JVM_OPTS='-Xmx1G -Xms1G '
+ versionLessThan b1.8
+ mc-image-helper compare-versions 1.20.1 lt b1.8
+ return 1
+ versionLessThan 1.7
+ mc-image-helper compare-versions 1.20.1 lt 1.7
+ return 1
+ rm -f /data/.mc-health.env
+ mcServerRunnerArgs=(--stop-duration "${STOP_DURATION:-60}s" --named-pipe "${CONSOLE_IN_NAMED_PIPE:-/tmp/minecraft-console-in}")
+ [[ -n '' ]]
+ [[ PAPER == \C\U\R\S\E\F\O\R\G\E ]]
+ [[ PAPER == \C\U\R\S\E\F\O\R\G\E ]]
+ [[ /data/folia-1.20.1-17.jar =~ run.sh ]]
+ '[' -f /data/bootstrap.txt ']'
+ log 'Starting the Minecraft server...'
+ local oldState
++ shopt -po xtrace
+ oldState='set -o xtrace'
+ shopt -u -o xtrace
[init] 2023-10-15 16:10:51-07:00 Starting the Minecraft server...
+ finalArgs=($JVM_XX_OPTS $JVM_OPTS $expandedDOpts)
+ [[ -n '' ]]
+ finalArgs+=(-jar "$SERVER")
+ finalArgs+=("$@" $EXTRA_ARGS)
+ isTrue false
+ case "${1,,}" in
+ return 1
+ isTrue false
+ case "${1,,}" in
+ return 1
+ isTrue false
+ case "${1,,}" in
+ return 1
+ exec mc-server-runner --stop-duration 60s --named-pipe /tmp/minecraft-console-in java -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -Xmx1G -Xms1G -jar /data/folia-1.20.1-17.jar
```

I don't see anything there that looks helpful, the only part that looks relevant (to me, at least) is:
```
+ exec /start-setupServerProperties
[mc-image-helper] 16:10:45.604 DEBUG : Setting property rcon.password to new value '***'
[mc-image-helper] 16:10:45.607 INFO  : Created/updated 1 property in /data/server.properties
```

However, that doesn't give any new information: the 2nd and 3rd lines are already in the logs without `DEBUG=true` set and the first line just says the name of the script it runs, which I already found using Github for my initial message that opened this issue. Is there any way to debug that file's execution specifically?

**Comment by itzg** [comment]
Thanks. Step 4 is indeed the one that breaks it.

I know there's still the issue to fix, but is there any way you can simply pass that via `MOTD` env var instead of editing server.properties directly? That's the primary use case and I have focused on fixing that one.

> However, that doesn't give any new information: the 2nd and 3rd lines are already in the logs without DEBUG=true set and the first line just says the name of the script it runs, which I already found using Github for my initial message that opened this issue. Is there any way to debug that file's execution specifically?

It did show the debug output of that tool

> [mc-image-helper] 16:10:45.604 DEBUG : Setting property rcon.password to new value '***'

There was only one value to change at that point.

**Comment by aaronjamt** [comment]
> I know there's still the issue to fix, but is there any way you can simply pass that via `MOTD` env var instead of editing server.properties directly? That's the primary use case and I have focused on fixing that one.

Yes, I'll switch my main server over to that during our next maintenance window.

> It did show the debug output of that tool

Ah, ok I miseed that


> > [mc-image-helper] 16:10:45.604 DEBUG : Setting property rcon.password to new value '***'
> 
> There was only one value to change at that point.

Interesting, it definitely changed the `motd=` line... I might have grabbed the wrong log file or something, I will try it again.

**Comment by itzg** [comment]
> Interesting, it definitely changed the motd= line... I might have grabbed the wrong log file or something, I will try it again.

To clarify, yes, it is indeed changing that line, but indirectly because it was not loading the properties file as UTF-8, changing the rcon.password property, and re-writing the whole file. I am testing out a fix now that will force that load as UTF-8. It's actually non-standard behavior that the Minecraft server is doing 😞

**Comment by aaronjamt** [comment]
> > Interesting, it definitely changed the motd= line... I might have grabbed the wrong log file or something, I will try it again.
> 
> To clarify, yes, it is indeed changing that line, but indirectly because it was not loading the properties file as UTF-8, changing the rcon.password property, and re-writing the whole file. I am testing out a fix now that will force that load as UTF-8. It's actually non-standard behavior that the Minecraft server is doing 😞

Ah, that makes a ton of sense. I just re-tested and made 100% sure it corrupted the MOTD text, it had the exact same log output (changing the rcon password but nothing else), was starting to get rather confused. Thanks for looking into this!

**Comment by itzg** [comment]
...it also doesn't help that the Minecraft server is re-writing the `server.properties` file. IMHO it should be only reading that file and not modifying it.

**Comment by aaronjamt** [comment]
> ...it also doesn't help that the Minecraft server is re-writing the `server.properties` file. IMHO it should be only reading that file and not modifying it.

Yeah, I agree. I think the logic is that allowing the server to modify it, it can "correct" certain options (for instance, convert the `difficulty=`  from the legacy 1/2/3 numeric values to the new easy/normal/hard text format), but I feel like the server should just log a warning that says `[WARN] Difficulty setting in server.properties uses legacy format (currently set to 1). Please change to "easy" instead.`, or something along those lines.

**Comment by itzg** [comment]
Currently building image should fix the latest scenario you confirmed. I'll create a follow up change to also write-out the file with UTF-8 encoding rather than escaping the Unicode characters.

**Comment by aaronjamt** [comment]
Yep, just tested the new build and it fixes it, at least on my testing server. I'll update my actual server during the next maintenance window but assuming that also works, I'm happy. Thanks for that!

**Comment by LapinFou** [comment]
Hi folks,

Sorry for my late answer (didn't have spare time this WE).
I can confirm that using the MOTD env variable is fixed with the latest version.

I didn't try to directly modify `server.properties`. I can try something if it can help.

**Comment by itzg** [comment]
Thanks for confirming the latest changes @aaronjamt and @LapinFou

**Comment by itzg** [comment]
Thanks @carsongmiller, I'll update the docs for that.

**Comment by JoCat** [comment]
I've tried adding MOTD via ENV (using Portainer), and everything is fine with the color codes, but the line translation is additionally escaped for some reason
![image](https://github.com/user-attachments/assets/26544f7c-9e2a-42cc-a327-33148238c637)
![image](https://github.com/user-attachments/assets/6bf9b321-ef96-43a6-a053-b9054e4e59e8)

in `server.properties`
![image](https://github.com/user-attachments/assets/a7612a37-0ed2-47aa-923b-f9342b399044)
