### ISSUE TITLE
latest Docker image fails to start

### ISSUE THREAD

**Issue by sempervent** [itzg/docker-minecraft-server#946]
This is reproducible with the following minimal code:

`docker run -e EULA=TRUE itzg/minecraft-server:latest`

The following is the error message:
```2021-07-03T13:59:47.994Z	INFO	mc-server-runner	Done
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 2 1000 1000 4096 Jul  2 21:24 /data'
[init] Resolved version given LATEST into 1.17
[init] Resolving type given VANILLA
[init] Downloading minecraft_server.1.17.jar ...
[init] Creating server.properties in /data/server.properties
[init] Disabling whitelist
[init] Setting whitelist to 'false' in /data/server.properties
[init] Setting white-list to 'false' in /data/server.properties
[init] Adding server-name with 'Dedicated Server' in /data/server.properties
[init] Setting server-port to '25565' in /data/server.properties
[init] Setting motd to 'A Vanilla Minecraft Server powered by Docker' in /data/server.properties
[init] Setting enable-rcon to 'true' in /data/server.properties
[init] Setting rcon.password to 'minecraft' in /data/server.properties
[init] Setting rcon.port to '25575' in /data/server.properties
[init] Setting level-name to 'world' in /data/server.properties
[init] Setting online-mode to 'true' in /data/server.properties
[init] Checking for JSON files.
[init] Setting initial memory to 1G and max to 1G
[init] Starting the Minecraft server...
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: JVMCFRE003 bad major version; class=net/minecraft/server/Main, offset=6
	at java.lang.ClassLoader.defineClassImpl(Native Method)
	at java.lang.ClassLoader.defineClassInternal(ClassLoader.java:396)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:357)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:682)
	at java.net.URLClassLoader.access$400(URLClassLoader.java:89)
	at java.net.URLClassLoader$ClassFinder.run(URLClassLoader.java:1086)
	at java.security.AccessController.doPrivileged(AccessController.java:774)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:589)
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:951)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:896)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:879)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:601)
2021-07-03T14:00:48.376Z	WARN	mc-server-runner	sub-process failed	{"exitCode": 1}
2021-07-03T14:00:48.376Z	INFO	mc-server-runner	Done```

**Comment by belleDESiRE** [comment]
Yes, also noticed this this morning. The 'latest' tag now comes with java8 instead of java16 (I guess by mistake).
I fixed it by getting the version with the 'java16' tag

**Comment by campfred** [comment]
Have you tried running the container with the tag `java16` for the image? That has fixed my case. It looks like the container image is not using a recent enough version of Java.

I'm not sure since I haven't seen _JNI errors_ before but a quick search around Google gave me results of people upgrading to 1.17 and not having a recent enough version of Java.
Which, if true, would be similar to the issue I'm having but with a different error code as I'm running a Paper server.

Here's what I'm getting :

```log
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxrwx 1 1000 100 840 Jul 3 10:21 /data'
[init] Resolved version given 1.17 into 1.17
[init] Resolving type given PAPER
[init] Removing old PaperMC versions ...
[init] Downloading PaperMC 1.17 (build 71) ...
[init] Getting plugins via Spiget
(...downloading a bunch of Spigot plugins...)
(...downloading a bunch of other plugins through direct URLs...)
[init] server.properties already created, skipping
[init] Using server icon from (removed link)...
[init] Converting image to 64x64 PNG...
[init] Checking for JSON files.
[init] Setting initial memory to 8G and max to 8G
[init] Starting the Minecraft server...
Minecraft 1.17 requires running the server with Java 16 or above. Download Java 16 (or above) from https://adoptopenjdk.net/

2021-07-03T10:23:09.074-0400 WARN mc-server-runner sub-process failed {"exitCode": 1}
2021-07-03T10:23:09.074-0400 INFO mc-server-runner Done
```

In my case, it's pretty explicit (or easier to read).
So, I tried running with tag `java16` and it booted right up after pulling the image.

**Comment by itzg** [comment]
Do a `docker pull itzg/minecraft-server:latest`. You're running an old image if it's still java 8.

**Comment by campfred** [comment]
> Do a `docker pull itzg/minecraft-server:latest`. You're running an old image if it's still java 8.

It was running Java 16 before though. It's when I pulled it again this morning after moving the data somewhere else.

**Comment by sempervent** [comment]
@itzg thanks for the suggestion, I'm using watchtower to monitor the docker images and pull the latest. I ensured the latest tag was up to date with a manual pull, but the issue persists. Overriding the entrypoint to go into bash results in the following:
```
java -version
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (build 1.8.0_292-b10)
Eclipse OpenJ9 VM (build openj9-0.26.0, JRE 1.8.0 Linux amd64-64-Bit Compressed Reference 20210421_1000 (JIT enabled, AOT enabled)
OpenJ9    - b4cc246d9
OMR        - l62e6f729
JCL           - 2a5e268814 based on jdk8u292-b10)```

**Comment by Slashbunny** [comment]
Looks like the `latest` image and the java8 image are the same:

![image](https://user-images.githubusercontent.com/368525/124360885-36a4a980-dbfa-11eb-9062-81d544216c52.png)

**Comment by itzg** [comment]
Good catch @Slashbunny ! I see now what the github actions change did. I'll fix this momentarily.

**Comment by itzg** [comment]
`latest` is now the correct "latest" and I'm double checking the variant builds now

![image](https://user-images.githubusercontent.com/988985/124364981-c0f50980-dc0a-11eb-96eb-af108dd65066.png)

**Comment by campfred** [comment]
I just pulled the `latest` image and I can confirm it is corrected!
Thank you very much for this prompt fix!

**Comment by sempervent** [comment]
@itzg Confirmed latest is running 16. Clowing this issue. Thank you!
